version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
    - netapp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - db:/data/db
      - configdb:/data/configdb
  backend:
    depends_on:
      - mongodb
    image: fileread:latest
    hostname: fileread
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - netapp
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./assets
        target: /usr/src/app/assets

volumes:
  db:
  configdb:

networks:
  netapp:
    driver: bridge